name: CI/CD
on:
  push:
    branches: [main, staging]
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

env:
  GH_PACKAGES_USERNAME: meboo
  GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MEBBOT }}
      - uses: DanySK/build-check-deploy-gradle-action@2.2.4
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./*/build/libs/*.jar
          
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MEBBOT }}
      - name: Download Build
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Semantic Release
        uses: eco-trip/semantic-release-action@v1.1
        with:
          token: ${{ secrets.MEBBOT }}
          checkout: false
