name: CI/CD
on:
  push:
    branches: [main, staging]
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: DanySK/build-check-deploy-gradle-action@2.1.5
      - name: Upload Build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./*/build/libs/*.jar
          
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Build
        uses: actions/download-artifact@v3
        with:
          name: build
      - name: Semantic Release
        uses: eco-trip/semantic-release-action@v1.0
        with:
          token: ${{ secrets.MEBBOT }}
          checkout: false
